#!/bin/sh
# path to instance	
GGP_PATH='/Users/35437/Projects/ggp/aem-6_2/crx-quickstart/bin'

echo
cd $GGP_PATH
echo
sh ./start
echo start process $(lsof -n -i4TCP:4502 | grep LISTEN | awk '{print $2}')

